all: 
	cd src; make
	cd test; make
	cd flattener; make
	cd vcd; make
	cd hcm_vcd; make
	cd sigvec; make

clean:
	cd src; make clean
	cd test; make clean
	cd flattener; make clean
	cd vcd; make clean
	cd hcm_vcd; make clean
	cd sigvec; make clean
